import Foundation

/// Built-in game library. `isEnabled` puts a game in the daily rotation; `isMust` makes it
/// required every day (set in Settings → Daily goal). The user's own list + LinkedIn games are
/// on by default; "similar" games live in the Library tab, one toggle away.
enum Catalog {
    static let defaults: [Game] = [
        // ── The user's list ────────────────────────────────────────────────────────
        Game(id: "murdle-crypt", name: "Murdle: Crypt", tagline: "Deduction in the dark — the harder daily",
             url: "https://murdle.com/crypt/", symbol: "moon.stars.fill", color: "#A855F7",
             category: .deduction, isEnabled: true),
        Game(id: "murdle", name: "Murdle", tagline: "Who, where, and with what? Daily logic-grid murder",
             url: "https://murdle.com/?mode=main", symbol: "magnifyingglass", color: "#F43F5E",
             category: .deduction, isEnabled: true),
        Game(id: "wordle", name: "Wordle", tagline: "The five-letter classic",
             url: "https://www.nytimes.com/games/wordle/index.html", symbol: "textformat.abc", color: "#22C55E",
             category: .word, isEnabled: true),
        Game(id: "globle", name: "Globle", tagline: "Find the mystery country by heat",
             url: "https://globle-game.com/", symbol: "globe.americas.fill", color: "#14B8A6",
             category: .geography, isEnabled: true),
        Game(id: "deduce", name: "Deduce", tagline: "Daily deduction puzzle",
             url: "https://deduce.studio/daily/anon", symbol: "brain.head.profile", color: "#F97316",
             category: .logic, isEnabled: true),
        Game(id: "word500", name: "Word500", tagline: "Wordle for power players — you only get the counts",
             url: "https://word500.com/game?mode=daily", symbol: "number", color: "#EAB308",
             category: .word, isEnabled: true),
        Game(id: "starlingdive", name: "Where is Starlingdive?", tagline: "Find the hidden town",
             url: "https://neokry.itch.io/where-is-starlingdive", symbol: "bird.fill", color: "#3B82F6",
             category: .geography, isEnabled: true),

        // ── LinkedIn dailies ───────────────────────────────────────────────────────
        Game(id: "li-queens", name: "Queens", tagline: "One crown per row, column and region",
             url: "https://www.linkedin.com/games/queens/", symbol: "crown.fill", color: "#7C3AED",
             category: .linkedin, isEnabled: true),
        Game(id: "li-tango", name: "Tango", tagline: "Fill the grid with suns and moons",
             url: "https://www.linkedin.com/games/tango/", symbol: "sun.max.fill", color: "#F59E0B",
             category: .linkedin, isEnabled: true),
        Game(id: "li-zip", name: "Zip", tagline: "Connect the numbers in order, fill every cell",
             url: "https://www.linkedin.com/games/zip/", symbol: "point.topleft.down.to.point.bottomright.curvepath.fill", color: "#0EA5E9",
             category: .linkedin, isEnabled: true),
        Game(id: "li-pinpoint", name: "Pinpoint", tagline: "Guess the category in five clues",
             url: "https://www.linkedin.com/games/pinpoint/", symbol: "scope", color: "#10B981",
             category: .linkedin, isEnabled: true),
        Game(id: "li-crossclimb", name: "Crossclimb", tagline: "Climb the word ladder",
             url: "https://www.linkedin.com/games/crossclimb/", symbol: "arrow.up.arrow.down", color: "#EC4899",
             category: .linkedin, isEnabled: true),
        Game(id: "li-minisudoku", name: "Mini Sudoku", tagline: "A 6×6 daily sudoku",
             url: "https://www.linkedin.com/games/mini-sudoku/", symbol: "square.grid.3x3.fill", color: "#6366F1",
             category: .linkedin, isEnabled: true),

        // ── Similar games (off by default, toggle in Library) ──────────────────────
        Game(id: "clues-by-sam", name: "Clues by Sam", tagline: "Daily deduction — who's innocent?",
             url: "https://cluesbysam.com/", symbol: "person.3.fill", color: "#8B5CF6", category: .deduction),
        Game(id: "puzzgrid", name: "Puzzgrid", tagline: "Only Connect-style wall",
             url: "https://puzzgrid.com/", symbol: "tablecells.fill", color: "#93C5FD", category: .deduction),
        Game(id: "connections", name: "Connections", tagline: "Group 16 words into 4 sets",
             url: "https://www.nytimes.com/games/connections", symbol: "square.grid.2x2.fill", color: "#A78BFA", category: .word),
        Game(id: "strands", name: "Strands", tagline: "Themed word search with a spangram",
             url: "https://www.nytimes.com/games/strands", symbol: "lasso", color: "#38BDF8", category: .word),
        Game(id: "spelling-bee", name: "Spelling Bee", tagline: "How many words from seven letters?",
             url: "https://www.nytimes.com/puzzles/spelling-bee", symbol: "hexagon.fill", color: "#FACC15", category: .word),
        Game(id: "mini", name: "The Mini", tagline: "NYT mini crossword",
             url: "https://www.nytimes.com/crosswords/game/mini", symbol: "squareshape.split.3x3", color: "#60A5FA", category: .word),
        Game(id: "letter-boxed", name: "Letter Boxed", tagline: "Words around the box",
             url: "https://www.nytimes.com/puzzles/letter-boxed", symbol: "square.dashed", color: "#F472B6", category: .word),
        Game(id: "quordle", name: "Quordle", tagline: "Four Wordles at once",
             url: "https://www.merriam-webster.com/games/quordle/", symbol: "square.grid.2x2", color: "#34D399", category: .word),
        Game(id: "waffle", name: "Waffle", tagline: "Swap letters into six words",
             url: "https://wafflegame.net/", symbol: "rectangle.grid.3x2.fill", color: "#FB923C", category: .word),
        Game(id: "squaredle", name: "Squaredle", tagline: "Boggle-style daily",
             url: "https://squaredle.app/", symbol: "square.grid.3x3.topleft.filled", color: "#A3E635", category: .word),
        Game(id: "contexto", name: "Contexto", tagline: "Guess the word by meaning",
             url: "https://contexto.me/", symbol: "text.bubble.fill", color: "#2DD4BF", category: .word),
        Game(id: "semantle", name: "Semantle", tagline: "Semantic-similarity guessing",
             url: "https://semantle.com/", symbol: "waveform.path", color: "#F87171", category: .word),
        Game(id: "worldle", name: "Worldle", tagline: "Guess the country by silhouette",
             url: "https://worldle.teuteuf.fr/", symbol: "globe", color: "#4ADE80", category: .geography),
        Game(id: "tradle", name: "Tradle", tagline: "Guess the country by its exports",
             url: "https://games.oec.world/en/tradle/", symbol: "shippingbox.fill", color: "#FBBF24", category: .geography),
        Game(id: "travle", name: "Travle", tagline: "Route between two countries",
             url: "https://travle.earth/", symbol: "map.fill", color: "#22D3EE", category: .geography),
        Game(id: "flagle", name: "Flagle", tagline: "Guess the flag, tile by tile",
             url: "https://www.flagle.io/", symbol: "flag.fill", color: "#F43F5E", category: .geography),
        Game(id: "geogrid", name: "GeoGrid", tagline: "Countries × categories grid",
             url: "https://www.geogridgame.com/", symbol: "globe.europe.africa.fill", color: "#818CF8", category: .geography),
        Game(id: "timeguessr", name: "TimeGuessr", tagline: "When and where was this photo taken?",
             url: "https://timeguessr.com/", symbol: "camera.fill", color: "#FB7185", category: .geography),
        Game(id: "chronophoto", name: "Chronophoto", tagline: "Guess the year of the photo",
             url: "https://www.chronophoto.app/", symbol: "clock.fill", color: "#C084FC", category: .trivia),
        Game(id: "nerdle", name: "Nerdle", tagline: "Wordle with equations",
             url: "https://nerdlegame.com/", symbol: "function", color: "#6EE7B7", category: .logic),
        Game(id: "puzzmo", name: "Puzzmo", tagline: "A whole page of dailies",
             url: "https://www.puzzmo.com/", symbol: "puzzlepiece.extension.fill", color: "#FDE047", category: .logic),
        Game(id: "framed", name: "Framed", tagline: "Guess the movie from six frames",
             url: "https://framed.wtf/", symbol: "film.fill", color: "#F59E0B", category: .screen),
        Game(id: "bandle", name: "Bandle", tagline: "Guess the song, instrument by instrument",
             url: "https://bandle.app/", symbol: "music.note", color: "#EC4899", category: .screen),
        Game(id: "box-office", name: "Box Office Game", tagline: "Rank the weekend's top films",
             url: "https://boxofficega.me/", symbol: "ticket.fill", color: "#FCD34D", category: .screen),
        Game(id: "guess-the-game", name: "Guess The Game", tagline: "Name the video game from screenshots",
             url: "https://guessthe.game/", symbol: "gamecontroller.fill", color: "#A78BFA", category: .trivia),
        Game(id: "redactle", name: "Redactle", tagline: "Un-redact the Wikipedia article",
             url: "https://redactle.net/", symbol: "text.redaction", color: "#9CA3AF", category: .trivia),
        Game(id: "wikitrivia", name: "Wikitrivia", tagline: "Order events on a timeline",
             url: "https://wikitrivia.tomjwatson.com/", symbol: "calendar", color: "#67E8F9", category: .trivia),
        Game(id: "metazooa", name: "Metazooa", tagline: "Guess the animal by taxonomy",
             url: "https://metazooa.com/", symbol: "pawprint.fill", color: "#86EFAC", category: .trivia),
        Game(id: "costcodle", name: "Costcodle", tagline: "Guess the Costco price",
             url: "https://costcodle.com/", symbol: "cart.fill", color: "#EF4444", category: .trivia),
    ]

    static func game(_ id: String) -> Game? { defaults.first { $0.id == id } }
}
